"""
WarmTalk 配置包
"""
from .model_config import (
    MODEL_NAME,
    USE_QUANTIZATION,
    QUANTIZATION_BITS,
    GENERATION_CONFIG,
    MAX_HISTORY_LENGTH,
    MAX_CONTEXT_LENGTH,
    SAVE_ONLY_USER_MESSAGES,
    PROMPT_VERSION,
    AUTO_ADJUST_FOR_CPU,
    CPU_MAX_NEW_TOKENS_LIMIT,
    CPU_SMALL_MODEL_MAX_TOKENS,
    USE_OFFLINE_MODE,
)
from .server_config import HOST, PORT, HEALTH_CHECK_INTERVAL, LOG_LEVEL
